package com.googlecode.scheme2ddl.db2.aspect;

import com.googlecode.scheme2ddl.db2.domain.Db2LookInfo;
import org.aspectj.lang.annotation.After;
import org.aspectj.lang.annotation.AfterReturning;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobParameters;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * @author ar
 * @since Date: 05.04.2015
 */
@Aspect
@Component
public class Db2LookInfoStatAspect {
    private List<Db2LookInfo> listExludedByFilter;

    public Db2LookInfoStatAspect() {
        this.listExludedByFilter = Collections.synchronizedList(new ArrayList<Db2LookInfo>());
    }

    @AfterReturning(pointcut = "execution(boolean com.googlecode.scheme2ddl.db2.IsAlterTableAutoGeneratedPredicate.evaluate(..)) &&"
            + "args(object)",
            returning = "retVal")
    public void exludedByFilter(Object object, boolean retVal) {
        if (retVal == false ) {
            listExludedByFilter.add((Db2LookInfo) object);
        }
    }

    @Before("execution(* org.springframework.batch.core.launch.JobLauncher.run(..))")
    public void clearStatistic() {
        this.listExludedByFilter = Collections.synchronizedList(new ArrayList<Db2LookInfo>());
    }

    @After("execution(* org.springframework.batch.core.launch.JobLauncher.run(..)) &&" +
            " args(job, jobParameters)")
    public void printStatistic(Job job, JobParameters jobParameters) {
        String schemaName = jobParameters.getString("schemaName");
        if (!listExludedByFilter.isEmpty()) {
            prettyPrint(schemaName);
        }
    }

    /**
     *
     * @param schemaName
     * @param listExludedByConfig
     * @param listSkippedBySQLError
     */
    public void prettyPrint(String schemaName) {
        String lSep = System.getProperty("line.separator");
        StringBuilder sb = new StringBuilder();
        sb.append(lSep);
        sb.append("-------------------------------------------------------");
        sb.append(lSep);
        sb.append(" R E P O R T    F I L T E R E D    S T A T E M E N T S ");
        sb.append(lSep);
        sb.append("-------------------------------------------------------");
        sb.append(lSep);
        sb.append(String.format("%d alter table with auto generated sequence values statements was filtered", listExludedByFilter.size()));
        sb.append(lSep);
        sb.append(lSep);

       System.out.println(sb.toString());

    }

}
